### PR TITLE
Added Ubuntu gettext domain support

### PR DESCRIPTION
**Pull request by Lt-Henry**
This patch may solve issue [854](https://github.com/albertlauncher/albert/issues/854). There is room for improvment, sure, ie: gettext domain may be defined but not present, so some sort of heuristic may decide best avaialable translation (desktop vs gettext)

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
I have no clue what this is about. Is this available on all platforms or will we get problems if I merge this? Fedora, Opensuse, BSD, arch?

**Comment by ManuelSchneid3r** [comment]
@Lt-Henry ?

**Comment by Lt-Henry** [comment]
I've not tested.... but it just looks for a Ubuntu key inside .desktop file. Nothing should happen if the key does not exists. I mean, default translation is selected. It is safe for non Ubuntu distros.

**Comment by ManuelSchneid3r** [comment]
What happens on systems like BSD?

**Comment by Lt-Henry** [comment]
The patch just looks for "X-Ubuntu-Gettext-Domain" key inside desktop, and gets a name and generic name using gettext, instead of names provided by current .desktop file. That key shouldn't be in any Linux or BSD distro but Ubuntu based ones.

**Comment by ManuelSchneid3r** [comment]
Sure but this PR includes libintl.h. Which is GNU. A quick search scares me off:
https://www.google.com/search?q=libintl.h+on+bsd&rlz=1C5CHFA_enDE755DE755&oq=libintl.h+on+bsd&aqs=chrome..69i57.2394j1j7&sourceid=chrome&ie=UTF-8

**Comment by Lt-Henry** [comment]
TBH, I dont know what happens on FreeBSD. Should be some sort of gettext support but I have no idea. I didnt have BSD in mind when I wrote the patch.

* The easy solution, is scope this patch in a macro detecting whenever it is being compiled on Linux/BSD. This is ugly :\
* Maybe Qt has some portable wrap around gettext.

I'll take a look at that.

**Comment by ManuelSchneid3r** [comment]
Afaik the desktop files have their own localization. No need for external l18n. Then

**Comment by ManuelSchneid3r** [comment]
I'll close this one for now. See https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html. Let me know what you think.

**Comment by ManuelSchneid3r** [comment]
I reconsidered this one, _if_ it makes problems on freebsd we could simply branch is using defines.

**Comment by ManuelSchneid3r** [comment]
recent version is now using gettext I changed a lot of other things as well in a general overhaul

**Comment by ManuelSchneid3r** [comment]
recent version is now using gettext I changed a lot of other things as well in a general [overhaul](https://github.com/albertlauncher/plugins/commit/8cd16aaaa31ea0b3c2488c3ef9c4e3860f84d832). thank you for pointing this out.

**Pull request closed without merging**
