### PR TITLE
Add Microsoft Edge support

### PR DESCRIPTION
**Pull request by xatier**
```
$ find .config/ -name Bookmarks
.config/microsoft-edge-dev/Default/Bookmarks
```

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
This is an extension request. If there is no urgent need for it, chances are that I will not implement it, unless I have personal interest in it. If you are not willing to implement it on your own, you'll have to wait until somebody else volunteers to do so. Please post your request on the [wiki page for extension suggestions](https://github.com/albertlauncher/albert/wiki/Extension-suggestions).

**Comment by xatier** [comment]
Hi @ManuelSchneid3r, thanks for the reply.

Sorry I am confused by "implement it on your own", isn't the implementation simply including the Edge's config path to this array? Also, the wiki page does not seem to be editable though. How should I propose this change request?

**Comment by david50407** [comment]
@ManuelSchneid3r This PR works for me with chromium-based Edge.
This is not an extension request, this PR added chromium-based edge browser's config path which allows Albert load bookmarks from edge's config folder (just like what albert to for chrome)

**Comment by ManuelSchneid3r** [comment]
It's not that easy. This list is not intended to contain all chromium based browsers. Its there for alternatives only. Like chromium and chromium dev. Pll may use Edge And chromium

**Comment by xatier** [comment]
Hi @ManuelSchneid3r, I'm not sure why we could have `Brave`, but not `Edge` on the list. Anyways, I ended up with maintaining my own Arch package w/ the patch.

**Comment by ManuelSchneid3r** [comment]
Well sure I could add it. merging Brave was a mistake in the first place. It is simply not that easy. We had issues where the extension did not work as expected because of this array. I prefer a proper solution which solves the problem rather than to continue the abuse. I will come back to this issue later when I work on the extension.

**Pull request closed without merging**
