### PR TITLE
Don't include non-python files in python extension list

### PR DESCRIPTION
**Pull request by Tyilo**

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
That acutally not an option since python modules may also be directories

**Comment by Tyilo** [comment]
See the code:

```
if (info.isFile() && !id.endsWith(".py"))
  continue;
```

**Comment by Tyilo** [comment]
@ManuelSchneid3r bump, this doesn't exclude directories.

**Comment by ManuelSchneid3r** [comment]
👌

**Comment by ManuelSchneid3r** [comment]
Have you ever tested this PR? I did not. I just released it and half of the python extensions disappeard.:angry:

**Comment by Tyilo** [comment]
I think the problem is that if you just make `albert` using `cmake` + `make` and run `albert` directly without running installing it, it will use the currently installed plugin library (or similar) instead of the one just build.

So I never saw the problem.

**Comment by ManuelSchneid3r** [comment]
Yup thats true. Just wrote an article on [how to correctly setup the dev env](https://steemit.com/albert/@manuelschneid3r/how-to-setup-the-albert-launcher-development-environment).

**Pull request merged**
