### PR TITLE
FreeBSD support.

### PR DESCRIPTION
**Pull request by jsm222**

### CODE REVIEW

**Comment by jsm222** [comment]
> doesnt it find the package without pkgconfig?

No, how would you do it yourself?

**Comment by ManuelSchneid3r** [comment]
Where is the package located? have you tried to modify the CMAKE_PREFIX_PATH?

**Comment by jsm222** [comment]
The ports framework in FreeBSD provides USES=localbase:ldflags which makes the CMakeLists.txt changed not needed
localbase:ldflags (I tend to forget that one) https://github.com/freebsd/freebsd-ports/blob/13174cc3af9de5ad3088a7dddd7e399015ebce21/x11/albert/Makefile#L18C36-L18C53. So the only change needed is here https://github.com/albertlauncher/plugins/pull/120/files#diff-6bf7f9b76e252a5559589167066f650c59f5cb54b7f73356239112cbb85587d7R127

**Comment by ManuelSchneid3r** [comment]
iirc i added this one in a former commit. i guess this one can be closed then. let me know if it builds.

**Pull request closed without merging**
