### PR TITLE
Updated websearch icons

### PR DESCRIPTION
**Pull request by nicolapreda**
I updated the icons for the plugin "websearch".

### CODE REVIEW

**Comment by AnishDe12020** [comment]
We need this to get merged ASAP. Tired of the old icons

**Comment by DenverCoder1** [comment]
This is great! Resolves https://github.com/albertlauncher/albert/issues/1003

Take a look at the differences in the icons I proposed in the issue above, though.

Particularly the Google and GitHub logos you provided look a bit off. Also I'm not sure if there's a need for the dark gray background on every logo.

This is what my current setup looks like, happy to hear your thoughts.

image

**Comment by DenverCoder1** [comment]
Why was this closed?

I was only offering some feedback

This is still the only PR for this issue and the icons in the fork can still be updated if necessary

**Comment by diskxo** [comment]
I'm sorry, I understood you had accepted it and I closed the pull request ..XD

**Comment by ManuelSchneid3r** [comment]
this pr is deprecated sorry. the websearch has its own repo. the icons are themed by the way which will break other themes

**Pull request closed without merging**
