### PR TITLE
[Applications] Implements albertlauncher/albert issue #890 by indexing apps in default XDG desktop

### PR DESCRIPTION
**Pull request by cyprienruffino**
Implements #890 by indexing apps in default XDG desktop

### CODE REVIEW

**Comment by idkCpp** [comment]
Was this meant to go into `master`?

**Comment by ManuelSchneid3r** [comment]
🤷‍♂️  I will delete dev branches in the submodules anyway. only in the albert repo Ill maintain a dev branch

**Comment by dshoreman** [comment]
Sadly the merge of this PR causes a rather long delay for me because my window manager (i3) does not *have* a Desktop *at all*, which causes it to fall back to scanning the **entire home directory and ALL subdirs** including symlinks that point to external drives.

Since `~/Desktop` is not a standard location to search for .desktop files (as previously mentioned by @ManuelSchneid3r in https://github.com/albertlauncher/albert/issues/890#issuecomment-721779338) I would suggest reverting this PR. Instead, if Desktop searching is absolutely necessary, an option to add a list of custom paths would probably be more flexible while not breaking any DE/WM that lack a desktop.

**Comment by uffejakobsen** [comment]
I'm one of them that are extremelyhappy for the desktop search feature :-)
 
I'll suggest that a check if the desktop dir/location exists - and only then it is added to the search list

**Comment by cyprienruffino** [comment]
The default behavior of `QStandardPaths::standardLocations(QStandardPaths::DesktopLocation)` is to return the same path as for 'QStandardPaths::HomeLocation'. This can be tested before the location is added to the list of directories to index.

**Comment by adabru** [comment]
Hi, in my case this still causes indexing of .desktop files in my whole home directory, which is slow. I'm on arch with albert version 0.17.2, also tried the albert-git package. Two months ago applications were certainly available almost immediately but now I have to wait 3-4 seconds.
Also tried starting with

```
XDG_DESKTOP_DIR="$HOME/Desktop" XDG_DATA_HOME="$HOME/.local/share" XDG_DATA_DIRS="/usr/share:/usr/local/share" albert
```

It still indexes desktop files in my whole home directory. Could it be that the code at <https://github.com/albertlauncher/plugins/blob/b4cac28be7b265027b00279baba14086d97c4d07/applications/src/extension.cpp#L237-L238> should rather use the member-variable `indexedDirs`? Because `indexedDirs` contains the check for `DesktopLocation` <> `HomeLocation` from the comment above. If you don't have a clue what is going on, I could experiment a little bit.

**Comment by uffejakobsen** [comment]
Strange - I'm on Arch Linux as well - and albert-0.17.2 and it works like a charm here

**Comment by adabru** [comment]
@uffejakobsen thanks for sharing!

In my logs I get:

```
17:16:09 [info:core] Initializing application
...
17:16:09 [info:core] Loading extension org.albert.extension.applications
17:16:09 [info:apps] Start indexing applications.
17:16:09 [debg:core] org.albert.extension.applications loaded in 0 milliseconds
...
17:16:09 [debg:applications] Loading file index from cache.
17:16:09 [debg:applications] Building inverted file index.
17:16:09 [info:applications] Start indexing files.
...
17:16:10 [debg:applications] Serializing files…
...
17:16:10 [debg:applications] Building inverted file index…
17:16:10 [info:applications] Indexed 6704 files in 1160 directories.
...
17:16:12 [debg:apps] Indexing desktop file: -home-adabru-setup-sqfs-mount.desktop
17:16:12 [debg:apps] Indexing desktop file: -home-adabru-work-ao-dist-__appImage-ia32-ao.desktop
...
17:16:12 [debg:apps] Indexing desktop file: albert.desktop
17:16:12 [debg:apps] Indexing desktop file: arduino.desktop
...
```

Maybe I confused [debg:apps] with applications? Still, the lines starting with `[debg:apps] Indexing desktop file: -home-adabru-` should not appear.

**Comment by dshoreman** [comment]
@adabru You didn't confuse anything :slightly_smiling_face:

While a new variable was introduced to track indexed locations - and that var *does* omit the homedir - the method changed in this PR wasn't actually updated to use it. I don't recall if the new var was used anywhere else but, essentially the initial indexing still uses its own set of paths *with* the homedir, hence the logs you see

---

@uffejakobsen If your setup has a desktop, you're not likely to see issues (it only becomes a problem when `XDG_DESKTOP_DIR="$HOME/"`). Could you post your ~/.config/user-dirs.dirs and which DE/WM you're using?

**Comment by adabru** [comment]
Thanks @dshoreman for your comment. I didn't know about ~/.config/user-dirs.dirs . My file looks like this:

```
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run.
# Format is XDG_xxx_DIR="$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
#
XDG_DESKTOP_DIR="$HOME/"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/"
XDG_PUBLICSHARE_DIR="$HOME/"
XDG_DOCUMENTS_DIR="$HOME/"
XDG_MUSIC_DIR="$HOME/"
XDG_PICTURES_DIR="$HOME/"
XDG_VIDEOS_DIR="$HOME/"
```

Changing XDG_DESKTOP_DIR to something other than home causes albert to omit .desktop entries in my home tree and it indexes my applications instantly again. My WM is swaywm.

**Pull request merged**
