### PR TITLE
Updated website logos

### PR DESCRIPTION
**Pull request by arghyadipchak**
Updated svg logos of webites of websearch plugin

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
Where did you have this icons from?

**Comment by ManuelSchneid3r** [comment]
I updated the icons a long time ago. If you are unhappy with them let me know

**Comment by ManuelSchneid3r** [comment]
They have just not been released yet

**Comment by arghyadipchak** [comment]
> They have just not been released yet

What do you mean?

**Comment by ManuelSchneid3r** [comment]
I changed them like two years ago but never released 0.18

**Pull request closed without merging**
