### PR TITLE
System commands update for KDE Plasma 6

### PR DESCRIPTION
**Pull request by kosantosbik**

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
Probably checking KDE_SESSION_VERSION=5 or 6 might make sense

**Comment by kosantosbik** [comment]
I still use plasma 5.27.4 on my laptop. The commands do work but after using Shutdown or Reboot, the open applications might not restart automatically when you log back in.

**Comment by kosantosbik** [comment]
Do you still want me to add version check?

**Comment by ManuelSchneid3r** [comment]
> Do you still want me to add version check?

well if it is necessary, yes. is there some sort of dbus interface documentation?

**Comment by kosantosbik** [comment]
I'm not sure where it says in the code/documentation but I made the change based on [this comment](https://discuss.kde.org/t/logout-reboot-and-shutdown-using-the-terminal/743/9) in KDE Discuss. It confirms the KSMServer will be removed and Shutdown API should be used. I think it is safe to merge.

**Comment by ManuelSchneid3r** [comment]
I cant find any documentation, but read several posts from KDE developers online stating that they changed this interface years ago. I dont plan to maintain backward compatibility for more than a few years (two recent ubuntu lts) so i guess this is fine. ty

**Comment by ManuelSchneid3r** [comment]
however please increment the minor version in the plugins cmake lists. if you are to lazy i  can put this in the next version of the plugin.

**Comment by kosantosbik** [comment]
No problem at all. Done.

**Comment by ManuelSchneid3r** [comment]
👍

**Pull request merged**
